#! /bin/sh

case $1 in 
    start)
        echo "Loading aesdchar driver **Test"
        aesdchar_load
        ;;
    stop)
        echo "Stopping aesdchar driver  **Test"
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac



exit 0
